name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 63038e5dd15c7c4b2e8b458a, dir: auntminnie.com, stack: leonis, account: smg, tenant: smg_all, rancher_label: science-medicine-group-auntminnie.com }
          - { id: 63038ec219398c102f8b457c, dir: auntminnieasia.com, stack: leonis, account: smg, tenant: smg_all, rancher_label: science-medicine-group-auntminnieasia.com }
          - { id: 63038e96d15c7cc42e8b4581, dir: auntminnieeurope.com, stack: leonis, account: smg, tenant: smg_all, rancher_label: science-medicine-group-auntminnieeurope.com }
          - { id: 63038e29475dbd6a2f8b457e, dir: drbicuspid.com, stack: leonis, account: smg, tenant: smg_all, rancher_label: science-medicine-group-drbicuspid.com }
          - { id: 62fc0ab6475dbd28008b459b, dir: labpulse.com, stack: virgon, account: smg, tenant: smg_all, rancher_label: science-medicine-group-labpulse.com }
          - { id: 63038dcdd15c7c4b2e8b4588, dir: scienceboard.net, stack: leonis, account: smg, tenant: smg_all, rancher_label: science-medicine-group-scienceboard.net }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      site_account: ${{ matrix.site.account }}
      site_dir: ${{ matrix.site.dir }}
      site_version: test
